[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[build.lifecycle]
  onBuild = "npx prisma generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]