[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure Prisma generates the client during build
[build.lifecycle]
  onBuild = "npx prisma generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]

[dev]
  framework = "astro"
  targetPort = 4321 