[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# For monorepo structure
[context.production]
  base = "/"

# You can add specific configurations for different sites in your monorepo
[context.production.environment]
  SITE_ID = "energy-forecast-hub"