[build]
  command = """
    rm -rf package-lock.json node_modules &&
    npm install &&
    npx prisma generate &&
    npm run build
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[build.lifecycle]
  onBuild = "npx prisma generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]