[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "npm run dev"
  port = 4321

[functions]
  external_node_modules = ["@prisma/client", "@astrojs/react"]
  node_bundler = "esbuild"

# Remove the catch-all redirect since this will be a sub-site
# The main site will handle routing to this site
