[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  external_node_modules = ["@prisma/client"]
  node_bundler = "esbuild"
  included_files = ["prisma/**"]

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 4321
  framework = "astro"
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/"
  to = "/curve-viewer"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"