[build]
  base = "/"
  command = "npx prisma generate && astro build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["@prisma/client"]
  node_bundler = "esbuild"
  included_files = ["prisma/**"]

[functions.ssr]
  included_files = ["prisma/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200